#!/bin/sh

AS=/usr/bin/as
CC=/usr/bin/clang
LD="$HOME/.brew/Cellar/llvm/16.0.6/bin/ld.lld"
OBJCOPY="$HOME/.brew/Cellar/llvm/16.0.6/bin/llvm-objcopy"

boot_bin() {
	"$AS" -target i386 -o out/boot.o src/boot/boot.s &&
	"$OBJCOPY" -O binary out/boot.o out/boot.bin
}

kernel_bin() {
	"$AS" -target i386 -o out/kernel.o src/kernel.s &&
	"$LD" -g -relocatable out/kernel.o -o out/kernel.all.o &&
	"$LD" --oformat=binary -T src/kernel.ld -o out/kernel.bin out/kernel.all.o
}

mkdir -p out &&
boot_bin &&
kernel_bin &&
cat out/{boot,kernel}.bin >out/floppy.img
